services:
  api:
    build: .
    container_name: blog_api_dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.development
    environment:
      - MONGO_URI=mongodb://mongo:27017/blog-api
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: blog_mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
