###register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email":"ali@yahoo.com",
  "password":"123456"
}


###login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email":"ali@yahoo.com",
  "password":"123456"
}

###logout
POST http://localhost:3000/api/auth/logout


###refreshToken
POST http://localhost:3000/api/auth/refreshToken


###current
GET http://localhost:3000/api/user/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWU4ODNlZTE2ZThlOGIzZGI2NDFkMzgiLCJyb2xlIjoidXNlciIsImlhdCI6MTc3Njg0NTgxMSwiZXhwIjoxNzc2ODQ5NDExLCJzdWIiOiJhY2Nlc3NUb2tlbiJ9.puRzJ2uZMyFneWoN4Shq9ULSuDZY0r8oOwqNDaj7Awc
