###register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email":"ali@yahoo.com",
  "password":"123456"
}


###login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email":"ali@yahoo.com",
  "password":"123456"
}

###logout
POST http://localhost:3000/api/auth/logout


###refreshToken
POST http://localhost:3000/api/auth/refreshToken


###current user
GET http://localhost:3000/api/user/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWU5ZDQ4YmQyODNhZDdiOTJmNDRiNTUiLCJyb2xlIjoidXNlciIsImlhdCI6MTc3NjkzMTk4OSwiZXhwIjoxNzc2OTM1NTg5LCJzdWIiOiJhY2Nlc3NUb2tlbiJ9.H5mYMNtRKUxl13TMSUdEJSoVmk6-YSdIhLVUaPmrFcA

###get user/id (admin)
GET http://localhost:3000/api/user/69e9d48bd283ad7b92f44b55
