###register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email":"ali@yahoo.com",
  "password":"123456"
}


###login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email":"ali@yahoo.com",
  "password":"123456"
}

###logout
POST http://localhost:3000/api/auth/logout


###refreshToken
POST http://localhost:3000/api/auth/refreshToken


###current user
GET http://localhost:3000/api/user/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWU5ZDQ4YmQyODNhZDdiOTJmNDRiNTUiLCJyb2xlIjoidXNlciIsImlhdCI6MTc3NjkzOTI0NywiZXhwIjoxNzc2OTQyODQ3LCJzdWIiOiJhY2Nlc3NUb2tlbiJ9.5MSqkJawZNSy7AaqHVecaOZTH-1u8EJJcMxqSCHYgf0

###get user/id (admin)
GET http://localhost:3000/api/user/69e9d48bd283ad7b92f44b55
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWU5ZDQ4YmQyODNhZDdiOTJmNDRiNTUiLCJyb2xlIjoidXNlciIsImlhdCI6MTc3NjkzOTI0NywiZXhwIjoxNzc2OTQyODQ3LCJzdWIiOiJhY2Nlc3NUb2tlbiJ9.5MSqkJawZNSy7AaqHVecaOZTH-1u8EJJcMxqSCHYgf0


###get ALL users (admin) {limit and offset is optional}
GET http://localhost:3000/api/user?limit=2&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWU5ZDQ4YmQyODNhZDdiOTJmNDRiNTUiLCJyb2xlIjoidXNlciIsImlhdCI6MTc3NjkzOTI0NywiZXhwIjoxNzc2OTQyODQ3LCJzdWIiOiJhY2Nlc3NUb2tlbiJ9.5MSqkJawZNSy7AaqHVecaOZTH-1u8EJJcMxqSCHYgf0

###update user
PUT http://localhost:3000/api/user/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWU5ZDQ4YmQyODNhZDdiOTJmNDRiNTUiLCJyb2xlIjoidXNlciIsImlhdCI6MTc3NjkzOTI0NywiZXhwIjoxNzc2OTQyODQ3LCJzdWIiOiJhY2Nlc3NUb2tlbiJ9.5MSqkJawZNSy7AaqHVecaOZTH-1u8EJJcMxqSCHYgf0

{
  "username":"ali"
}

###delete user/id (admin)
DELETE http://localhost:3000/api/user/69e9d48bd283ad7b92f44b55
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWU5ZDQ4YmQyODNhZDdiOTJmNDRiNTUiLCJyb2xlIjoidXNlciIsImlhdCI6MTc3Njk2NDEyMiwiZXhwIjoxNzc2OTY3NzIyLCJzdWIiOiJhY2Nlc3NUb2tlbiJ9.e24DlkZZ5rrG2abKtzTN1WncSUJQfyT6WMeNluO6MhM
